version: '3.8'

services:
  flask-proxy:
    build: .
    container_name: flask-proxy
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    depends_on: []
    networks:
      - proxy-net

networks:
  proxy-net:
    driver: bridge
